[build]
  command = "tsc && mkdir -p netlify/functions && cp dist/functions/* netlify/functions"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

